<?php
/**
 * The main template file.
 *
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file exists.
 * Learn more: http://codex.wordpress.org/Template_Hierarchy
 *
 * @package WordPress
 * @subpackage Twenty_Eleven
 */

get_header(); ?>


      <div id="pagewrapper">

        <div id="header">
          <h6><a href="#">HOME</a> / <a href="#">ABOUT THIS SITE</a> / <a href="#">CONTACT</a> </h6> 
          <div id="title_container">
          <h1 class="tright">MACON'S 2012 SPLOST</h1>
          <h3 class="subtitle">// Track Macon's SPLOST Project Funding</h3>
          </div>

        </div><!-- #header END -->

         <div id="bread_box">
          <div id="breadcrumbs">

            <div class="left"><p>Economic Development</p></div>
            <div class="right"><p>Downtown Corridor</p></div>
          </div><!-- #breadcrumbs END -->
         </div><!-- #bread_box END -->



        <div id="sidebar">
          <div class="button"><a href="#">SPLOST Overview</a></div>
          <div style="clear:both;"></div>
          <h2>SPLOST CATEGORIES & PROJECTS</h2>

          <div class="menu">
            <ul class="menu_cat">
            <li class="category ps"><a href="#">Public Safety</a></li>
            </ul>

            <ul>
            <li class="project ps"><a href="#">Storm Drainage</a></li>
            <li class="project ps second"><a href="#">Street Maintenance</a></li>
            <li class="project ps"><a href="#">GMA Lease Pool</a></li>
            <li class="project ps second"><a href="#">Public Safety Equipment</a></li>
            <li class="project ps"><a href="#">Public Safety Other</a></li>
            </ul>
         </div><!-- #menu END -->

         <div class="menu">
            <ul class="menu_cat">
            <li class="category dr"><a href="#">Debt Retirement</a></li>
            </ul>

            <ul>
            <li class="project dr"><a href="#">Debt Retirement</a></li>
            <li class="project dr second"><a href="#">Bond Repayment</a></li>
            </ul>
          </div><!-- #menu END -->

          <div class="menu">
            <ul class="menu_cat">
            <li class="category ed"><a href="#">Economic Development</a></li>
            </ul>

            <ul>
            <li class="project ed"><a href="#">Centreplex</a></li>
            <li class="project ed second"><a href="#">Downtown Corridor</a></li>
            </ul>
          </div><!-- #menu END -->

          <div class="menu">
            <ul class="menu_cat">
            <li class="category ra"><a href="#">Rec & Cultural Arts</a></li>
            </ul>

            <ul>
            <li class="project ra"><a href="#">Tubman Museum</a></li>
            <li class="project ra second"><a href="#">Bowden Golf</a></li>
            <li class="project ra"><a href="#">Rose Hill Cemetery</a></li>
            <li class="project ra second"><a href="#">Ft. Hawkins</a></li>
            </ul>
          </div><!-- #menu END -->


          </div><!-- #sidebar END -->


<div id="maincontainer">
<div id="welcomepage">
  <h5 class="welcometop">Message from Mayor Reichart</h5>
  <p class="quote">Welcome to Macon's 2011 SPLOST website. Here you'll be able to track all of Macon's projects being funding by the 2011 SPLOST. We're thankful Macon's support of SPLOST and happy to provide you this site so that you can know where and when your SPLOST money is at work. </p>
  <h5>What is SPLOST?</h5>
  <p>SPLOST stands for Special Purpose Local Option Sales Tax. In many places this is called a bond referendum or penny-tax. In Month, voters in Macon-Bibb County voted to raise their local sales tax by 1%. Over the next 6 years the money generated by the 1% increase will go directly to the city of Macon to fund special projects.</p>
  <p>This money will go towards funding many projects the city could not otherwise afford to do within its annual budget. Projects like maintaining and <a class="ralink" href="#">updating parks</a>, <a class="pslink" href="#">repairing roads</a> and paying off the <a class="drlink" href="#">city's debt</a>.</p><p>
  </p><h5>How to use this site</h5>
  <div id="half">
    <p>Use the left column to navigate through categories, projects and the overview. </p>
  <p>This site breaks down the city of Macon's SPLOST responsibilities into pages like so:</p>
  </div>
  <div class="welcome_menu">
    <ul>
    <li><div class="button"><a href="#">1 Overview Page</a></div></li>
    <li class="category ps"><a href="#">4 Category Pages</a></li>
    <li class="project ra"><a href="#">and 14 Project Pages</a></li>
    
  </ul>
  </div>
  
  
  </div>
    
    
    
    </div>
        <div id="footer">
          <p>Built by Code for America for Macon, Georgia.
          </div><!-- #footer end -->

      </div><!-- #pagewrapper end -->


<?php get_sidebar(); ?>
<?php get_footer(); ?>